apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfa-auth-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sfa-auth-service
  template:
    metadata:
      labels:
        app: sfa-auth-service
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: sfa-auth-service
        image: 10.10.10.202/pico/sfa-auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sfa-auth-service
  namespace: default
spec:
  selector:
    app: sfa-auth-service
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
