apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfa-auth-service
  namespace: sfa-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sfa-auth-service
  template:
    metadata:
      labels:
        app: sfa-auth-service
    spec:
      containers:
      - name: sfa-auth-service
        image: 10.10.10.202/pico/sfa-auth-service:v1
        ports:
        - containerPort: 8001
      imagePullSecrets:
      - name: harbor-registry-secret
