apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfa-master-data-service
  namespace: sfa-master-data-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sfa-master-data-service
  template:
    metadata:
      labels:
        app: sfa-master-data-service
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - name: sfa-master-data-service
        image: 10.10.10.202/pico/sfa-master-data-service:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8003
