apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfa-reports-service
  namespace: sfa-reports-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sfa-reports-service
  template:
    metadata:
      labels:
        app: sfa-reports-service
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - name: sfa-reports-service
        image: 10.10.10.202/pico/sfa-reports-service:v2
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: sfa-reports-service-env
        ports:
        - containerPort: 8000
