apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfa-trade-marketing
  namespace: sfa-trade-marketing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sfa-trade-marketing
  template:
    metadata:
      labels:
        app: sfa-trade-marketing
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - name: sfa-trade-marketing
        image: 10.10.10.202/pico/sfa-trade-marketing:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8003
