apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfa-stock-management-service
  namespace: sfa-stock-management-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sfa-stock-management-service
  template:
    metadata:
      labels:
        app: sfa-stock-management-service
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - name: sfa-stock-management-service
        image: 10.10.10.202/pico/sfa-stock-management-service:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8003
